version: "3"
services:
    node-latest:
        image: "emsa16/realtimegame-backend:node-latest"
        build:
            context: .
            dockerfile: docker/Dockerfile-node-latest
        environment:
            - START_CHAT=${START_CHAT}
        ports:
            - "8110:8099"
            - "${WS_DBWEBB_PORT:-1556}:1337"
        volumes:
            - ./:/home/node/app
            - /home/node/app/node_modules/
    node-10:
        image: "emsa16/realtimegame-backend:node-10"
        build:
            context: .
            dockerfile: docker/Dockerfile-node-10
            - START_CHAT=${START_CHAT}
        ports:
            - "8100:8099"
            - "${WS_DBWEBB_PORT:-1557}:1337"
        volumes:
            - ./:/home/node/app
            - /home/node/app/node_modules/
    node-8:
        image: "emsa16/realtimegame-backend:node-8"
        build:
            context: .
            dockerfile: docker/Dockerfile-node-8
        environment:
            - START_CHAT=${START_CHAT}
        ports:
            - "8088:8099"
            - "${WS_DBWEBB_PORT:-1558}:1337"
        volumes:
            - ./:/home/node/app
            - /home/node/app/node_modules/
